---

- name: Get node power status
  hosts: all
  gather_facts: false

  tasks:

    - name: Get cluster power status
      command: i2cget -y 1 0x57 0xf2
      changed_when: false
      check_mode: false
      become: true
      register: cluster_power_status
      run_once: true

    # Ansible and Jinja both lack any bitwise operators. Luckily, (ba)sh does.
    # This is too noisy.
    - name: Node status
      shell: 
        cmd: '(( {{ cluster_power_status.stdout }} & {{ i2c_mask }} ))'
        executable: /bin/bash
      changed_when: false
      check_mode: false
      connection: local
