---

- name: Poweron a node
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: node
      prompt: "Which node to poweron (node)?"
      private: false

  tasks:
    - name: Ensure node exists
      assert:
        that: hostvars[node]['i2c_mask'] is defined
        fail_msg: "I have no record for {{ node }}."
        quiet: true

    - name: Get cluster power status
      command: i2cget -y 1 0x57 0xf2
      changed_when: false
      check_mode: false
      delegate_to: '{{ (node=="node1") | ternary ("node2", "node1") }}'
      become: true
      register: cluster_power_status

    # Ansible and Jinja both lack any bitwise operators. Luckily, (ba)sh does.
    - name: Get node power status
      shell: echo $(( {{ cluster_power_status.stdout }} & {{ hostvars[node]['i2c_mask'] }} ))
      changed_when: false
      check_mode: false
      connection: local
      register: node_power_status

    - name: Powering on {{ node }}
      command: i2cset -m {{ hostvars[node]['i2c_mask'] }} -y 1 0x57 0xf2 0xff
      changed_when: true
      become: true
      delegate_to: '{{ (node=="node1") | ternary ("node2", "node1") }}'
      when: node_power_status.stdout == "0"
