---

- name: Install Docker
  hosts: all

  vars:
    docker_apt_key: https://download.docker.com/linux/debian/gpg
    docker_group: docker
    docker_cfg_path: /etc/docker/daemon.json
    gluster_volume_alias: gluster

  tasks:
    - name: Install pre-requisite packages
      ansible.builtin.package:
        name: '{{ docker_prerequisites }}'
        state: present
      become: true

    - name: Install Docker Apt Key
      ansible.builtin.apt_key:
        url: '{{ docker_apt_key }}'
        state: present
      become: true

    - name: Add Docker Apt Repository
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=arm64]
          https://download.docker.com/linux/debian
          {{ ansible_distribution_release }}
          stable
        filename: docker-ce
        state: present
      become: true

    - name: Install Docker Packages
      ansible.builtin.package:
        name: '{{ docker_packages }}'
        state: present
      become: true

    - name: Set Docker config
      ansible.builtin.copy:
        dest: '{{ docker_cfg_path }}'
        content: |
          {
            "log-driver": "local"
          }
        mode: '0644'
        owner: root
        group: root
      become: true
      notify: Restart Docker

    - name: Add unprivileged user to Docker's group
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        groups: '{{ docker_group }}'
        append: true
      become: true

    - name: Enable Docker Services
      ansible.builtin.service:
        name: '{{ item }}'
        state: started
        enabled: true
      with_items:
        - containerd.service
        - docker.service

    - name: Get docker plugins
      ansible.builtin.command:
        cmd: docker plugin list
      register: plugin_list
      check_mode: false
      changed_when: false
      tags: doit

    - name: Install gluster volume plugin
      ansible.builtin.command:
        cmd: >
          docker plugin install
            --alias {{ gluster_volume_alias }}
            mochoa/glusterfs-volume-plugin
            --grant-all-permissions
            --disable
      register: plugin
      changed_when: '"Installed plugin mochoa/glusterfs-volume-plugin" in plugin.stdout'
      when:
        - 'gluster_volume_alias ~ ":latest" not in plugin_list.stdout'
        - not ansible_check_mode
      notify:
        - Set Volume Servers
        - Enable Volume Plugin
      tags: doit

    # We can safely assume that cmdline.txt will never be blank/empty/missing
    - name: Adjust cmdline.txt
      ansible.builtin.lineinfile:
        path: /boot/cmdline.txt
        regexp: '^(.*?)( {{ item }}(.*)|)$'
        line: '\1 {{ item }}\3'
        backrefs: true
      become: true
      with_items:
        - cgroup_enable=memory
        - cgroup_memory=1
        - swapaccount=1
        - net.ifnames=0
      notify: Mark for Reboot

  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker.service
        state: restarted
      become: true

    - name: Set Volume Servers
      ansible.builtin.command:
        cmd: docker plugin set {{ gluster_volume_alias }} SERVERS={{ inventory_hostname }}
      changed_when: true

    - name: Enable Volume Plugin
      ansible.builtin.command:
        cmd: docker plugin enable {{ gluster_volume_alias }}
      changed_when: true

    - name: Mark for Reboot
      ansible.builtin.include_tasks: includes/mark-for-reboot.yml
      vars:
        reason: 'Append cgroup paramters to cmdline.txt'
