---

- name: Create gluster filesystems
  hosts: all

  gather_facts: false

  vars:
    fstype: xfs
    # xfs has fewer issues with extended attributes than ext4 has

  tasks:
    - name: Install XFS
      package:
        name: xfsprogs
        state: present
      become: true

    - name: Create filesystems
      community.general.filesystem:
        dev: '{{ item.dev }}'
        fstype: '{{ fstype }}'
        opts: -L {{ item.label | default(omit) }}
        state: present
      become: true
      with_items: '{{ mounts }}'

    - name: Mount filesystems
      ansible.posix.mount:
        path: /data/glusterfs/{{ item.name }}/brick1
        # https://docs.gluster.org/en/latest/Administrator-Guide/Brick-Naming-Conventions/
        src: '{{ (item.label is defined) | ternary ( "LABEL=" ~ (item.label|default(omit)), item.dev) }}'
        fstype: '{{ fstype }}'
        opts: defaults,noatime
        state: mounted
      become: true
      with_items: '{{ mounts }}'
