---

- name: Enable localhost heartbeat
  hosts: all

  vars:
    key_filename: id_heartbeat
    ssh_dir: /root/.ssh

  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: '{{ ssh_dir }}'
        state: directory
        owner: root
        group: root
        mode: 'u=rwx,g=,o='
      become: true

    - name: Install heartbeat key
      ansible.builtin.copy:
        dest: '{{ ssh_dir }}/{{ key_filename }}'
        content: '{{ heartbeat_key }}'
        owner: root
        group: root
        mode: 'u=r,g=,o='
      no_log: false
      become: true

    - name: Enable heartbeat key
      ansible.posix.authorized_key:
        key: '{{ heartbeat_key_pub }}'
        user: root
        comment: "Heartbeat key"
        key_options: 'command="/usr/bin/hostname",from="::1",restrict'
      become: true

    # TODO: ensure localhost host key is known to ssh

    - name: Start the heartbeat
      ansible.builtin.cron:
        name: ssh_heartbeat
        cron_file: ssh_heartbeat
        user: root
        job: >
          /bin/sh -c 'if [ "$(ssh -i {{ ssh_dir }}/{{ key_filename }} ::1
          /usr/bin/hostname)" != "$(/usr/bin/hostname)" ]; then
          /usr/sbin/reboot; fi'
        day: '*'
        hour: '*'
        minute: '*/5'
        month: '*'
        state: present
        weekday: '*'
      become: true

    - name: Test filesystem readonly-ness
      ansible.builtin.cron:
        name: filesystem_heartbeat
        cron_file: filesystem_heartbeat
        user: root
        job: >
          /bin/sh -c 'if ! /usr/bin/touch /root/.heartbeat;
          then /usr/sbin/reboot; fi'
        day: '*'
        hour: '*'
        minute: '*/5'
        month: '*'
        state: present
        weekday: '*'
      become: true
