---

- name: Set hostname to MAC
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Gathering Facts
      setup:
      when: module_setup is not defined

  tasks:
    - name: Make hostname from MAC address
      set_fact:
        hostname: '{{
          ansible_facts[ ansible_default_ipv4.alias][ "macaddress" ]
          | regex_replace ("^.* ","")
          | regex_replace (":","")
        }}'
      check_mode: false

    - name: Set hostname
      hostname:
        name: '{{ hostname }}'
      become: true

    - name: Fix /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^(127.0.1.1\s+)'
        line: '\1{{ hostname }}'
        backrefs: true
        state: present
      become: true

