---

- name: Initialize keepalived
  hosts: all

  vars:
    repository: jaqque
    image: keepalived
    tag: 2.1.5
    image_name: '{{ repository }}/{{ image }}:{{ tag }}'
    packages:
      - python3-jsondiff
      -  python3-yaml

  pre_tasks:
    - name: Install prerequisite packages
      package:
        name: '{{ packages }}'
        state: present
      become: true

  tasks:
    - name: Load the image
      community.docker.docker_image:
        name: '{{ image_name }}'
        source: load
        load_path: '/srv/store/containers/{{ image }}-{{ tag }}.tar'

    - name: keepalive the swarm
      community.docker.docker_stack:
        name: keepalived
        compose:
          - version: '3'
            services:
              keepalived:
                image: '{{ image_name }}'
                cap_add:
                  - NET_ADMIN
                  - NET_BROADCAST
                  - NET_RAW
                deploy:
                  mode: global
                  #resources:
                    #limit:
                      #cpus: '0.50'
                      #memory: '50M'
                  restart_policy:
                    condition: on-failure
                    max_attempts: 3
                network_mode: host
      tags:
        - doit

