---

- name: Set up intitial ansible.cfg
  hosts: localhost

  vars:
    ansible_cfg: "{{ playbook_dir }}/ansible.cfg"

  tasks:
    - name: Get upstream ansible.cfg
      ansible.legacy.uri:
        url: https://raw.githubusercontent.com/ansible/ansible/v{{ ansible_version.string }}/examples/ansible.cfg
        dest: '{{ ansible_cfg  }}'
        creates: '{{ ansible_cfg }}'

    - name: Override defaults
      community.general.ini_file:
        path: '{{ ansible_cfg }}'
        section: '{{ item.section }}'
        option: '{{ item.option }}'
        value: '{{ item.value }}'
        state: present
      with_items:
        - { section: defaults, option: forks, value: 7 }
        - { section: defaults, option: gathering, value: smart }
        - { section: defaults, option: inventory, value: hosts }
        - { section: defaults, option: stdout_callback, value: debug }
        - { section: defaults, option: vault_password_file, value: '{{ ansible_user_dir }}/.ansible-vault-password' }

    - name: Install required collections and roles
      command:
        cmd: ansible-galaxy install -r requirements.yml
        chdir: '{{ playbook_dir }}'
      changed_when: '"was installed successfully" in galaxy.stdout'
      register: galaxy
      #notify: Installed Collections and Roles

  handlers:
    - name: Installed Collections and Roles
      debug:
        msg: '{{ item }}'
      when: '"was installed successfully" in item'
      with_items: '{{ galaxy.stdout_lines }}'
