---

- name: Set default password
  hosts: all
  gather_facts: false

  tasks:
    - name: Set pi password
      ansible.builtin.user:
        name: pi
        password: '{{ crypted_password }}'
      become: true
