---

- name: Reboot System
  hosts: all
  serial: 1

  vars:
    force: false
  tasks:
    - name: Get reboot required status
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    # We don't need to demote a manager; rebooting one keeps Raft consensus
    # glusterfs, similarly, should be just fine.
#   - block:
#     - name: Get Docker Manager status
#       community.docker.docker_host_info:
#       register: manager
#       when: manager is undefined
#     - block:
#       - name: Pick and Promote Manager
#         debug: 
#           msg: I choose you, Pikachu!
#       - name: Demote Manager
#         debug:
#           msg: I am a manager. Demote me.
#       when: manager.host_info.Swarm.ControlAvailable
#     when:
#       - reboot_required.stat.exists or force|bool

    - name: Reboot
      reboot:
      become: true
      when: reboot_required.stat.exists or force|bool

