---

collections:
  - name: community.general
    version: 9.4.0
  - name: community.docker
    version: 3.12.1

  # these are dependencies of community.general
  # https://github.com/ansible-collections/community.general/blob/1.3.4/galaxy.yml
  - name: ansible.netcommon
    version: 6.1.3
  - name: community.kubernetes
    version: 1.1.1
  - name: google.cloud
    version: 1.4.1
