---

- import_playbook: localhost.yml
- import_playbook: hostname.yml
- import_playbook: passwd.yml
- import_playbook: ssh_keys.yml
- import_playbook: filesystems.yml
- import_playbook: gluster.yml
- import_playbook: docker.yml
- import_playbook: i2c.yml
