---

- name: Install ssh public keys
  hosts: all
  gather_facts: false

  tasks:
    - name: Install keys for pi user
      authorized_key:
        user: pi
        key: '{{ lookup("file", lookup("env", "HOME") ~ "/.ssh/authorized_keys") }}'
      become: true
