---

ansible_python_interpreter: /usr/bin/python3
crypted_password: '{{ vault_crypted_password }}'
boot_txt: /boot/config.txt
i2c_dtoverlay: |
  dtoverlay=i2c1,pins_44_45
  dtoverlay=i2c-rtc,mcp7940x

# gluster volumes
# https://docs.gluster.org/en/latest/Administrator-Guide/Brick-Naming-Conventions/
gluster_path: /data/glusterfs/%%item%%/brick1/brick
mounts:
  - { name: cifs, dev: /dev/mmcblk0p3, label: CIFS }
  - { name: store, dev: /dev/mmcblk0p4, label: STORE }

# docker vars
# https://docs.docker.com/engine/install/debian/
docker_prerequisites:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
docker_packages:
  - containerd.io
  - docker-ce
  - docker-ce-cli

cifs_user: jaqque
cifs_password: '{{ vault_cifs_password }}'

# netdata monitoring
netdata_pathname: '/usr/sbin/netdata'
netdata_installer_url: 'https://my-netdata.io/kickstart.sh'
netdata_installer_checksum: 'md5:18f839c20f5389c5f2b3c71025858082'
netdata_release_channel: 'nightly'
netdata_claim_token: '{{ vault_netdata_claim_token }}'
netdata_claim_rooms: '{{ vault_netdata_claim_rooms }}'
netdata_claim_url: 'https://app.netdata.cloud'
netdata_config_pathname: '/etc/netdata/netdata.conf'


# ssh heartbeat
# The key fingerprint is:
# SHA256:6gKwRfI6EWhfvIEzUFksm8IPdOcUlWS2mbnMMjg/ruE Heartbeat Key
# The key's randomart image is:
# +--[ED25519 256]--+
# |..o.*o+=.        |
# |+o.B Bo.=        |
# |+=o @ o=         |
# |o+o+.oo .        |
# | *+o o +S        |
# |+ ..o o.         |
# | . o o.          |
# |  . +..          |
# |   E.o.          |
# +----[SHA256]-----+
heartbeat_key: '{{ vault_heartbeat_key }}'
heartbeat_key_pub: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINBQvX5tIqXc1YEDaFAR4zBIZNtBVBibM6folWnvf7Ol Heartbeat Key'
