---

ansible_python_interpreter: /usr/bin/python3
ansible_user: pi
crypted_password: '{{ vault_crypted_password }}'
boot_txt: /boot/config.txt
i2c_dtoverlay: |
  dtoverlay=i2c1,pins_44_45
  dtoverlay=i2c-rtc,mcp7940x

# gluster volumes
mounts:
  - { name: cifs, dev: /dev/mmcblk0p3, label: CIFS }
  - { name: store, dev: /dev/mmcblk0p4, label: STORE }
