---

ansible_python_interpreter: /usr/bin/python3
crypted_password: '{{ vault_crypted_password }}'
boot_txt: /boot/config.txt
i2c_dtoverlay: |
  dtoverlay=i2c1,pins_44_45
  dtoverlay=i2c-rtc,mcp7940x

# gluster volumes
# https://docs.gluster.org/en/latest/Administrator-Guide/Brick-Naming-Conventions/
gluster_path: /data/glusterfs/%%item%%/brick1/brick
mounts:
  - { name: cifs, dev: /dev/mmcblk0p3, label: CIFS }
  - { name: store, dev: /dev/mmcblk0p4, label: STORE }
